#!/bin/sh
#
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

if [ "$JAVA_HOME" = "" ]; then
    echo "JAVA_HOME not set"
    exit 1
else
   if [ ! -x "${JAVA_HOME}/bin/java" ]
   then
       echo "JAVA_HOME/bin/java not found, check JAVA_HOME ($JAVA_HOME)"
       exit 1
   fi
fi

if [ $# -eq 0 ]; then
   EnterPW_oldmods=`stty -g`
   printf "Enter password >> "
   stty -echo
   read PW
   stty "$EnterPW_oldmods"
   printf "\nRetype password >> "
   stty -echo
   read PW1
   stty "$EnterPW_oldmods"
   printf "\n"
   if [ "$PW" != "$PW1" ]; then
     echo "passwords are not equal"
     exit 1
   fi
else
  PW=$*
fi

${JAVA_HOME}/bin/java -cp WEB-INF/lib/reporting.jar com.sun.grid.arco.util.CryptoHandler $PW
